"""World — the tile map and its generation.

A World is a 2D grid of tile types plus an underlying heightmap.
Terrain generation uses multi-octave value noise, self-contained (no scipy).
"""
from __future__ import annotations
import enum
import numpy as np
from dataclasses import dataclass
from .config import WorldConfig


class Tile(enum.IntEnum):
    """Tile types. Values fit in uint8; new types may be added later."""
    WATER    = 0
    BEACH    = 1
    GRASS    = 2
    FOREST   = 3
    HILL     = 4
    MOUNTAIN = 5
    LAVA     = 6  # not generated by terrain; appears after Volcano
    BLIGHTED = 7  # post-disaster
    HOLY     = 8  # post-miracle

    @classmethod
    def from_height(cls, h: float, cfg: WorldConfig) -> "Tile":
        if h < cfg.sea_level:        return cls.WATER
        if h < cfg.beach_thresh:     return cls.BEACH
        if h < cfg.forest_thresh:    return cls.GRASS
        if h < cfg.hill_thresh:      return cls.FOREST
        if h < cfg.mountain_thresh:  return cls.HILL
        return cls.MOUNTAIN


@dataclass
class World:
    """A 2D world of tiles plus the heightmap that produced it."""
    width: int
    height: int
    seed: int
    tiles: np.ndarray      # shape (height, width) dtype=uint8
    heightmap: np.ndarray  # shape (height, width) dtype=float32, normalized 0..1

    @classmethod
    def generate(cls, cfg: WorldConfig) -> "World":
        rng = np.random.default_rng(cfg.seed)
        heightmap = _value_noise_2d(cfg.width, cfg.height, rng,
                                     octaves=5, persistence=0.5)
        # Normalize to [0, 1]
        lo, hi = float(heightmap.min()), float(heightmap.max())
        heightmap = (heightmap - lo) / (hi - lo + 1e-9)
        # Island-shaping vignette so edges trend toward water
        yy, xx = np.mgrid[0:cfg.height, 0:cfg.width].astype(np.float32)
        cx, cy = cfg.width / 2.0, cfg.height / 2.0
        nx = (xx - cx) / cx
        ny = (yy - cy) / cy
        dist = np.sqrt(nx * nx + ny * ny)
        vignette = np.clip(1.0 - 0.45 * dist, 0.0, 1.0).astype(np.float32)
        heightmap = (heightmap * vignette).astype(np.float32)
        # Re-normalize after vignette so thresholds still apply meaningfully
        lo, hi = float(heightmap.min()), float(heightmap.max())
        heightmap = (heightmap - lo) / (hi - lo + 1e-9)

        # Vectorized tile classification
        tiles = np.full((cfg.height, cfg.width), int(Tile.MOUNTAIN), dtype=np.uint8)
        tiles[heightmap < cfg.mountain_thresh] = int(Tile.HILL)
        tiles[heightmap < cfg.hill_thresh]     = int(Tile.FOREST)
        tiles[heightmap < cfg.forest_thresh]   = int(Tile.GRASS)
        tiles[heightmap < cfg.beach_thresh]    = int(Tile.BEACH)
        tiles[heightmap < cfg.sea_level]       = int(Tile.WATER)

        return cls(
            width=cfg.width,
            height=cfg.height,
            seed=cfg.seed,
            tiles=tiles,
            heightmap=heightmap.astype(np.float32),
        )

    def in_bounds(self, x: int, y: int) -> bool:
        return 0 <= x < self.width and 0 <= y < self.height


def _value_noise_2d(width: int, height: int, rng: np.random.Generator,
                     octaves: int = 5, persistence: float = 0.5) -> np.ndarray:
    """Multi-octave value noise. Each octave is a small random grid
    bilinearly upscaled to the final resolution and summed with halved
    amplitude. Produces smooth, fractal-ish terrain.
    """
    result = np.zeros((height, width), dtype=np.float32)
    amplitude = 1.0
    total_amp = 0.0
    for octave in range(octaves):
        # Grid size grows with each octave: 4, 8, 16, 32, 64...
        gh = min(height, 4 * (2 ** octave))
        gw = min(width, 4 * (2 ** octave))
        small = rng.random((gh, gw)).astype(np.float32)
        result += _bilinear_upscale(small, height, width) * amplitude
        total_amp += amplitude
        amplitude *= persistence
    return result / total_amp


def _bilinear_upscale(small: np.ndarray, h: int, w: int) -> np.ndarray:
    """Bilinear-upscale a 2D array to (h, w). Pure numpy, no scipy."""
    sh, sw = small.shape
    y_idx = np.linspace(0, sh - 1, h, dtype=np.float32)
    x_idx = np.linspace(0, sw - 1, w, dtype=np.float32)
    y0 = np.floor(y_idx).astype(np.int32)
    x0 = np.floor(x_idx).astype(np.int32)
    y1 = np.clip(y0 + 1, 0, sh - 1)
    x1 = np.clip(x0 + 1, 0, sw - 1)
    fy = (y_idx - y0).astype(np.float32)
    fx = (x_idx - x0).astype(np.float32)
    out = np.empty((h, w), dtype=np.float32)
    for j in range(h):
        a = small[y0[j], x0]
        b = small[y0[j], x1]
        c = small[y1[j], x0]
        d = small[y1[j], x1]
        top = a + fx * (b - a)
        bot = c + fx * (d - c)
        out[j] = top + fy[j] * (bot - top)
    return out
