"""World — the tile map and its generation.

A World is a 2D grid of tile types plus an underlying heightmap.
Terrain generation uses multi-octave value noise, self-contained (no scipy).

P3 PR2 adds `mutate_tile()` plus the small biome-walkability helpers the
Raise/Lower powers and their drown rule depend on. `mutate_tile` is the
single seam where tile, heightmap, and food state move in lockstep; the
caller (main.py) wraps it with a repaint_cb + drown step.
"""
from __future__ import annotations
import enum
import numpy as np
from dataclasses import dataclass
from typing import Callable, Optional, TYPE_CHECKING
from .config import WorldConfig

if TYPE_CHECKING:
    from .food import FoodField


class Tile(enum.IntEnum):
    """Tile types. Values fit in uint8; new types may be added later."""
    WATER    = 0
    BEACH    = 1
    GRASS    = 2
    FOREST   = 3
    HILL     = 4
    MOUNTAIN = 5
    LAVA     = 6  # not generated by terrain; appears after Volcano
    BLIGHTED = 7  # post-disaster
    HOLY     = 8  # post-miracle

    @classmethod
    def from_height(cls, h: float, cfg: WorldConfig) -> "Tile":
        if h < cfg.sea_level:        return cls.WATER
        if h < cfg.beach_thresh:     return cls.BEACH
        if h < cfg.forest_thresh:    return cls.GRASS
        if h < cfg.hill_thresh:      return cls.FOREST
        if h < cfg.mountain_thresh:  return cls.HILL
        return cls.MOUNTAIN


# -- biome metadata (P3 PR2) -------------------------------------------------

# Tiles a citizen can stand on / walk through. The drown rule fires for any
# citizen left on a tile NOT in this set after a Raise or Lower. Kept in
# sync with WALKABLE_TILES in citizen.py — duplicated here so world.py can
# answer the question without importing citizen.
WALKABLE_TILE_IDS: frozenset[int] = frozenset({
    int(Tile.GRASS), int(Tile.BEACH), int(Tile.FOREST), int(Tile.HOLY),
})


def is_walkable_tile(tile_id: int) -> bool:
    """True if a citizen can stand on this tile."""
    return int(tile_id) in WALKABLE_TILE_IDS


# Canonical heightmap value per tile, picked at the midpoint of each
# elevation band. The exact numbers don't drive gameplay — `tiles` does —
# they only affect any future renderer that shades by height. Raise/Lower
# sets the new tile's heightmap to its canonical band value so the visual
# steps cleanly between ranks.
_TILE_HEIGHT_BAND: dict[int, float] = {
    int(Tile.WATER):    0.15,
    int(Tile.BEACH):    0.32,
    int(Tile.GRASS):    0.45,
    int(Tile.FOREST):   0.62,
    int(Tile.HILL):     0.77,
    int(Tile.MOUNTAIN): 0.92,
    int(Tile.LAVA):     0.45,
    int(Tile.BLIGHTED): 0.45,
    int(Tile.HOLY):     0.50,
}


def heightmap_for(tile_id: int) -> float:
    """Canonical heightmap value (0..1) for a tile, used post-mutation."""
    return _TILE_HEIGHT_BAND.get(int(tile_id), 0.5)


# repaint_cb signature: (world, tx, ty) -> None.
RepaintCallback = Callable[["World", int, int], None]


def mutate_tile(world: "World", food: "FoodField",
                 repaint_cb: Optional[RepaintCallback],
                 tx: int, ty: int, new_tile: int) -> bool:
    """Mutate `(tx, ty)` to `new_tile`. Updates world.tiles, world.heightmap,
    and the food field's cap/regen/food in lockstep, then invokes
    `repaint_cb(world, tx, ty)` so the renderer can patch the world surface.

    The drown rule lives *outside* this function — the caller checks
    `is_walkable_tile(new_tile)` and calls `citizens.drown_at(...)` itself.
    Keeping that seam separate lets tests exercise the world/food update
    without a CitizenManager, and keeps world.py from importing citizen.py.

    Returns True on a real mutation; False if the tile was already that
    type or the coordinate was OOB (in which case repaint_cb is not invoked
    and the caller should skip its drown / log / chrome steps).
    """
    tx = int(tx); ty = int(ty); new_tile = int(new_tile)
    if not world.in_bounds(tx, ty):
        return False
    old = int(world.tiles[ty, tx])
    if old == new_tile:
        return False
    # Lookup the biome row for the new tile. Lazy import dodges the
    # food.py -> world.py top-level import cycle.
    from .food import _biome_table
    table = _biome_table(food.cfg)
    cap, regen = table.get(new_tile, (0.0, 0.0))
    world.tiles[ty, tx] = np.uint8(new_tile)
    world.heightmap[ty, tx] = np.float32(heightmap_for(new_tile))
    food.cap[ty, tx] = np.float32(cap)
    food.regen[ty, tx] = np.float32(regen)
    # Clamp standing food to the (possibly new) cap.
    if float(food.food[ty, tx]) > float(cap):
        food.food[ty, tx] = np.float32(cap)
    food.version += 1
    if repaint_cb is not None:
        repaint_cb(world, tx, ty)
    return True


@dataclass
class World:
    """A 2D world of tiles plus the heightmap that produced it."""
    width: int
    height: int
    seed: int
    tiles: np.ndarray      # shape (height, width) dtype=uint8
    heightmap: np.ndarray  # shape (height, width) dtype=float32, normalized 0..1

    @classmethod
    def generate(cls, cfg: WorldConfig) -> "World":
        rng = np.random.default_rng(cfg.seed)
        heightmap = _value_noise_2d(cfg.width, cfg.height, rng,
                                     octaves=5, persistence=0.5)
        # Normalize to [0, 1]
        lo, hi = float(heightmap.min()), float(heightmap.max())
        heightmap = (heightmap - lo) / (hi - lo + 1e-9)
        # Island-shaping vignette so edges trend toward water
        yy, xx = np.mgrid[0:cfg.height, 0:cfg.width].astype(np.float32)
        cx, cy = cfg.width / 2.0, cfg.height / 2.0
        nx = (xx - cx) / cx
        ny = (yy - cy) / cy
        dist = np.sqrt(nx * nx + ny * ny)
        vignette = np.clip(1.0 - 0.45 * dist, 0.0, 1.0).astype(np.float32)
        heightmap = (heightmap * vignette).astype(np.float32)
        # Re-normalize after vignette so thresholds still apply meaningfully
        lo, hi = float(heightmap.min()), float(heightmap.max())
        heightmap = (heightmap - lo) / (hi - lo + 1e-9)

        # Vectorized tile classification
        tiles = np.full((cfg.height, cfg.width), int(Tile.MOUNTAIN), dtype=np.uint8)
        tiles[heightmap < cfg.mountain_thresh] = int(Tile.HILL)
        tiles[heightmap < cfg.hill_thresh]     = int(Tile.FOREST)
        tiles[heightmap < cfg.forest_thresh]   = int(Tile.GRASS)
        tiles[heightmap < cfg.beach_thresh]    = int(Tile.BEACH)
        tiles[heightmap < cfg.sea_level]       = int(Tile.WATER)

        return cls(
            width=cfg.width,
            height=cfg.height,
            seed=cfg.seed,
            tiles=tiles,
            heightmap=heightmap.astype(np.float32),
        )

    def in_bounds(self, x: int, y: int) -> bool:
        return 0 <= x < self.width and 0 <= y < self.height


def _value_noise_2d(width: int, height: int, rng: np.random.Generator,
                     octaves: int = 5, persistence: float = 0.5) -> np.ndarray:
    """Multi-octave value noise. Each octave is a small random grid
    bilinearly upscaled to the final resolution and summed with halved
    amplitude. Produces smooth, fractal-ish terrain.
    """
    result = np.zeros((height, width), dtype=np.float32)
    amplitude = 1.0
    total_amp = 0.0
    for octave in range(octaves):
        # Grid size grows with each octave: 4, 8, 16, 32, 64...
        gh = min(height, 4 * (2 ** octave))
        gw = min(width, 4 * (2 ** octave))
        small = rng.random((gh, gw)).astype(np.float32)
        result += _bilinear_upscale(small, height, width) * amplitude
        total_amp += amplitude
        amplitude *= persistence
    return result / total_amp


def _bilinear_upscale(small: np.ndarray, h: int, w: int) -> np.ndarray:
    """Bilinear-upscale a 2D array to (h, w). Pure numpy, no scipy."""
    sh, sw = small.shape
    y_idx = np.linspace(0, sh - 1, h, dtype=np.float32)
    x_idx = np.linspace(0, sw - 1, w, dtype=np.float32)
    y0 = np.floor(y_idx).astype(np.int32)
    x0 = np.floor(x_idx).astype(np.int32)
    y1 = np.clip(y0 + 1, 0, sh - 1)
    x1 = np.clip(x0 + 1, 0, sw - 1)
    fy = (y_idx - y0).astype(np.float32)
    fx = (x_idx - x0).astype(np.float32)
    out = np.empty((h, w), dtype=np.float32)
    for j in range(h):
        a = small[y0[j], x0]
        b = small[y0[j], x1]
        c = small[y1[j], x0]
        d = small[y1[j], x1]
        top = a + fx * (b - a)
        bot = c + fx * (d - c)
        out[j] = top + fy[j] * (bot - top)
    return out
